CREATE DATABASE choripan;
USE choripan;
CREATE TABLE FABRICANTE(
 CODIGO INT PRIMARY KEY,
 NOMBRE VARCHAR(100));

CREATE TABLE PRODUCTO(
 CODIGO INT PRIMARY KEY,
 NOMBRE VARCHAR(100) NOT NULL,
 PRECIO FLOAT NOT NULL,
 CODIGO_FAB INT,
 FOREIGN KEY(CODIGO_FAB) REFERENCES FABRICANTE(CODIGO));